name: RPi_4_camera_py312
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyqt=6.6
  - opencv
  - numpy>=1.26
  - pillow
  - psutil
  - pyyaml
  - pyinstaller
  - requests
  - paramiko
  - pip
  - pip:
    - pypylon>=4.2.0  # conda-forge 沒有，使用 pip 安裝
