backup_config: true
buffer_point: 950
camera:
  auto_reconnect: true
  default_fps: 30
  default_height: 480
  default_width: 640
  last_source: null
  preferred_source: null
  reconnect_timeout: 5
check_updates: true
detection:
  bg_history: 20000
  bg_threshold: 16
  binary_threshold: 30
  buffer_point: 180
  canny_threshold1: 50
  canny_threshold2: 110
  detect_shadows: true
  max_object_area: 150
  min_object_area: 10
  roi_default_position: 0.25416666666666665
  roi_height: 16
  target_count: 200
  track_tolerance_x: 64
  track_tolerance_y: 48
display:
  font_size: medium
  show_performance: true
font_size: large
general:
  auto_backup: true
  auto_check_update: true
  language: zh_TW
language: zh_TW
max_object_area: 150
min_object_area: 10
photo_analysis:
  auto_analyze: true
  max_circle_radius: 300
  min_circle_radius: 50
  quality_threshold: 9.0
  save_captured: true
  save_directory: captured_images
roi_default_position: 0.5
show_performance: true
system:
  backup_config: true
  check_updates: true
  language: zh_TW
  log_level: INFO
target_count: 1000
theme: light
ui:
  font_size: large
  object_box_color: '#FF0000'
  roi_line_color: '#00FF00'
  show_performance: true
  theme: light
  video_quality: high
  window_state:
    height: 600
    position_x: null
    position_y: null
    width: 800
